FROM golang:1.18

RUN apt-get update
RUN apt-get -y install python3

WORKDIR $GOPATH/src/github.com/rpc/
COPY . .

# Fetch dependencies
RUN go mod tidy

# Build the binary. for grpc gateway
RUN go build -o worker ./cmd/worker

RUN chmod +x ./worker

ENTRYPOINT ["./worker"]
